classDiagram
    class BigBangHarness {
        <<Driver>>
        +startE2EPlayback(userId, assetId) void
    }

    class AuthService {
        <<service>>
        +validateSession(jwt) Boolean
    }

    class CatalogService {
        <<service>>
        +getTitle(assetId) Title
    }

    class PlayerStreamer {
        <<service>>
        +openManifest(assetId) String
    }

    class BillingService {
        <<service>>
        +assertEntitlement(userId, assetId) Boolean
    }

    BigBangHarness --> AuthService : instancia
    BigBangHarness --> CatalogService : instancia
    BigBangHarness --> PlayerStreamer : instancia
    BigBangHarness --> BillingService : instancia
    PlayerStreamer --> AuthService : usa
    PlayerStreamer --> CatalogService : usa
    PlayerStreamer --> BillingService : usa
    AuthService --> BillingService : usa
