@startuml
skinparam classAttributeIconSize 0

class PlaybackOrchestrator {
  - roteadorBorda: ICdnEdgeRouter
  + PlaybackOrchestrator(roteador: ICdnEdgeRouter)
  + startPlayback(userId: String, assetId: String): PlaybackTicket
}

interface ICdnEdgeRouter {
  + resolveManifest(assetId: String, region: String): ManifestDto
}

class CdnEdgeRouterStub <<Stub (Simulador)>> {
  - respostaPadrao: Boolean
  + resolveManifest(assetId: String, region: String): ManifestDto
  + simular404(): void
  + simularTimeout(): void
}

PlaybackOrchestrator --> ICdnEdgeRouter : utiliza
CdnEdgeRouterStub ..|> ICdnEdgeRouter : implementa
@enduml
