classDiagram
    class SmokeSuite {
        <<Driver de Fumaca>>
        +test_login_retorna_200() void
        +test_manifesto_m3u8_retorna_200() void
        +test_health_retorna_200() void
    }

    class ApiGateway {
        <<service>>
        +login(credenciais) JwtToken
        +obterManifesto(assetId) String
        +health() Status
    }

    class AuthService {
        <<service>>
        +autenticar(credenciais) JwtToken
    }

    class PlaybackOrchestrator {
        <<service>>
        +obterMasterM3u8(assetId) String
    }

    SmokeSuite --> ApiGateway : rotas vitais
    ApiGateway --> AuthService : login
    ApiGateway --> PlaybackOrchestrator : manifesto
