classDiagram
    class GeradorEstresse {
        <<Driver de Carga>>
        +simularEstreia(vu) void
    }

    class ApiGateway {
        <<service>>
        +receberRequisicao() HttpResponse
    }

    class CircuitBreaker {
        +permitir() Boolean
        +abrir() void
        +rejeitarRapido() HttpResponse
    }

    class PlaybackOrchestrator {
        <<service>>
        +startPlayback(userId, assetId) PlaybackTicket
    }

    GeradorEstresse --> ApiGateway : 500000 VU
    ApiGateway --> CircuitBreaker : consulta
    CircuitBreaker --> PlaybackOrchestrator : se fechado
    CircuitBreaker --> GeradorEstresse : 429 ou 503 se aberto
